apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - servicemonitor-ml-api.yaml
  - servicemonitor-backend-api.yaml
  - prometheus-rules.yaml
  - grafana-dashboard-overview.yaml
  - grafana-dashboard-ml-api.yaml
  - grafana-dashboard-backend-api.yaml
