apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ml-api
  namespace: monitoring
  labels:
    app: ml-api
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - ml-api
  selector:
    matchLabels:
      app: ml-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
